# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.1.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.1.0")
   message(FATAL_ERROR "CMake >= 3.1.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.1.0...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::Core)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::Core
add_library(Qt6::Core STATIC IMPORTED)

set_target_properties(Qt6::Core PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION;QT_COORD_TYPE"
  INTERFACE_COMPILE_DEFINITIONS "QT_CORE_LIB"
  INTERFACE_COMPILE_OPTIONS "\$<\$<OR:\$<CXX_COMPILER_ID:GNU>,\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>,\$<CXX_COMPILER_ID:IntelLLVM>>:-ffunction-sections;-fdata-sections>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/QtCore;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Qt6::Platform;\$<LINK_ONLY:Qt6::GlobalConfigPrivate>;\$<LINK_ONLY:WrapZLIB::WrapZLIB>;\$<LINK_ONLY:Qt6::PlatformModuleInternal>;WrapAtomic::WrapAtomic;\$<LINK_ONLY:Qt6::ZlibPrivate>;\$<LINK_ONLY:WrapPCRE2::WrapPCRE2>"
  INTERFACE_LINK_OPTIONS "\$<\$<OR:\$<CXX_COMPILER_ID:GNU>,\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>,\$<CXX_COMPILER_ID:IntelLLVM>>:-Wl,--gc-sections>"
  INTERFACE_QT_COORD_TYPE "double"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:${_IMPORT_PREFIX}/metatypes/qt6core_metatypes.json>"
  QT_DISABLED_PRIVATE_FEATURES "clock_gettime;copy_file_range;system_doubleconversion;dladdr;futimens;getauxval;getentropy;glib;icu;winsdkicu;windows_ioring;windows_ioring_skip_builder_param_checks;inotify;jemalloc;journald;system_libb2;linkat;liburing;system_pcre2;poll_ppoll;poll_pollts;poll_poll;posix_sem;posix_shm;pthread_clockjoin;pthread_condattr_setclock;pthread_timedjoin;qqnx_pps;renameat2;slog2;syslog;sysv_sem;sysv_shm;dup3;accept4;vxpipedrv;backtrace;cxx20_format;cxx23_stacktrace;cpp_winrt;lttng;etw;ctf;poll_exit_on_error;openssl_hash;async_io;use_bfd_linker;use_gold_linker;use_lld_linker;use_mold_linker;android_style_assets;developer_build;private_tests;doc_snippets;debug;elf_private_full_version;no_direct_extern_access;x86intrin;sse2;sse3;ssse3;sse4_1;sse4_2;avx;f16c;avx2;avx512f;avx512er;avx512cd;avx512pf;avx512dq;avx512bw;avx512vl;avx512ifma;avx512vbmi;avx512vbmi2;aesni;vaes;rdrnd;rdseed;shani;lsx;lasx;mips_dsp;mips_dspr2;neon;arm_crc32;arm_crypto;arm_sve;localtime_r;localtime_s;posix_fallocate;force_system_libs;force_bundled_libs;system_zlib;stdlib_libcpp;dbus;dbus_linked;network;printsupport;sql;testlib;xml;libudev;openssl;dlopen;relocatable;libcpp_hardening;relro_now_linker;android_16kb_pages"
  QT_DISABLED_PUBLIC_FEATURES "clock_monotonic;cxx11_future;cxx17_filesystem;glib;inotify;jemalloc;sharedmemory;systemsemaphore;cpp_winrt;library;timezone_tzdb;shared;debug_and_release;separate_debug_info;appstore_compliant;simulator_and_device;rpath;force_asserts;framework;cxx20;cxx2a;cxx2b;cxx2c;reduce_relocations;wasm_simd128;wasm_exceptions;wasm_jspi;zstd;thread;dbus;openssl_linked;opensslv11;opensslv30"
  QT_ENABLED_PRIVATE_FEATURES "doubleconversion;broken_threadlocal_dtors;memmem;memrchr;mimetype_database;poll_select;sha3_fast;hijricalendar;timezone_locale;datetimeparser;forkfd_pidfd;pcre2;gc_binaries;reduce_exports;gui;widgets;intelcet;glibc_fortify_source;trivial_auto_var_init_pattern;stack_protector;stack_clash_protection;libstdcpp_assertions;cross_compile;largefile"
  QT_ENABLED_PUBLIC_FEATURES "std_atomic64;mimetype;regularexpression;shortcut;xmlstream;xmlstreamreader;xmlstreamwriter;textdate;datestring;process;processenvironment;temporaryfile;settings;filesystemwatcher;filesystemiterator;itemmodel;proxymodel;sortfilterproxymodel;identityproxymodel;transposeproxymodel;concatenatetablesproxymodel;stringlistmodel;translation;easingcurve;animation;gestures;jalalicalendar;islamiccivilcalendar;timezone;commandlineparser;cborstreamreader;cborstreamwriter;permissions;version_tagging;static;cross_compile;pkg_config;signaling_nan;future;concurrent;test_gui;test_squish;static;cross_compile;plugin_manifest;intelcet;glibc_fortify_source;trivial_auto_var_init_pattern;stack_protector;stack_clash_protection;libstdcpp_assertions;static;reduce_exports"
  QT_QMAKE_PRIVATE_CONFIG "pcre2;cross_compile;largefile"
  QT_QMAKE_PUBLIC_CONFIG "static;cross_compile;plugin_manifest;intelcet;glibc_fortify_source;trivial_auto_var_init_pattern;stack_protector;stack_clash_protection;libstdcpp_assertions"
  QT_QMAKE_PUBLIC_QT_CONFIG "static;reduce_exports"
  _qt_config_module_name "core"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtCore"
  _qt_module_interface_name "Core"
  _qt_module_relative_include_dir "../../../include/QtCore"
  _qt_package_name "Qt6Core"
  _qt_package_version "6.11.1"
  _qt_private_module_target_name "CorePrivate"
  _qt_sbom_cydx_bom_serial_number_uuid "35478d7e-8d38-5f9e-a74e-3c020abb89e9"
  _qt_sbom_cydx_external_bom_link "urn:cdx:35478d7e-8d38-5f9e-a74e-3c020abb89e9/1#SPDXRef-Package-qtbase-qt-module-Core-ba1e0fef0406"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_MODULE"
  _qt_sbom_package_name "Core"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-module-Core-ba1e0fef0406"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.1+dirty-host-linux-x86_64-target-codeos-x86_64-f6d5add6-08f7-51ee-b9c7-3dbe432a76d4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-ba1e0fef0406"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-ba1e0fef0406:SPDXRef-Package-qtbase-qt-module-Core-ba1e0fef0406"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/Qt6CoreTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Platform" "Qt6::GlobalConfigPrivate" "Qt6::PlatformModuleInternal" "Qt6::ZlibPrivate" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
