QT.core_private.VERSION = 6.11.1
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/6.11.1 $$QT_MODULE_INCLUDE_BASE/QtCore/6.11.1/QtCore
QT.core_private.frameworks = 
QT.core_private.depends = core
QT.core_private.uses = 
QT.core_private.module_config = v2 staticlib internal_module
QT.core_private.enabled_features = doubleconversion broken-threadlocal-dtors memmem memrchr mimetype-database poll_select sha3-fast hijricalendar timezone_locale datetimeparser forkfd_pidfd pcre2 gc_binaries reduce_exports gui widgets intelcet glibc_fortify_source trivial_auto_var_init_pattern stack_protector stack_clash_protection libstdcpp_assertions cross_compile largefile
QT.core_private.disabled_features = clock-gettime copy_file_range system-doubleconversion dladdr futimens getauxval getentropy glib icu winsdkicu windows-ioring windows-ioring-skip-builder-param-checks inotify jemalloc journald system-libb2 linkat liburing system-pcre2 poll_ppoll poll_pollts poll_poll posix_sem posix_shm pthread_clockjoin pthread_condattr_setclock pthread_timedjoin qqnx_pps renameat2 slog2 syslog sysv_sem sysv_shm dup3 accept4 vxpipedrv backtrace cxx20_format cxx23_stacktrace cpp-winrt lttng etw ctf poll-exit-on-error openssl-hash async-io use_bfd_linker use_gold_linker use_lld_linker use_mold_linker android-style-assets developer-build private_tests doc_snippets debug elf_private_full_version no_direct_extern_access x86intrin sse2 sse3 ssse3 sse4_1 sse4_2 avx f16c avx2 avx512f avx512er avx512cd avx512pf avx512dq avx512bw avx512vl avx512ifma avx512vbmi avx512vbmi2 aesni vaes rdrnd rdseed shani lsx lasx mips_dsp mips_dspr2 neon arm_crc32 arm_crypto arm_sve localtime_r localtime_s posix_fallocate force-system-libs force-bundled-libs system-zlib stdlib-libcpp dbus dbus-linked network printsupport sql testlib xml libudev openssl dlopen relocatable libcpp_hardening relro_now_linker android_16kb_pages
QMAKE_LIBS_LIBATOMIC = 
QMAKE_LIBS_LIBRT = 
