QT.core.VERSION = 6.11.1
QT.core.name = QtCore
QT.core.module = Qt6Core
QT.core.libs = $$QT_MODULE_LIB_BASE
QT.core.ldflags = 
QT.core.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtCore
QT.core.frameworks = 
QT.core.bins = $$QT_MODULE_BIN_BASE
QT.core.depends =  
QT.core.run_depends = zlib_private
QT.core.uses = libatomic
QT.core.module_config = v2 staticlib
QT.core.CONFIG = moc resources
QT.core.DEFINES = QT_CORE_LIB
QT.core.enabled_features = std-atomic64 mimetype shortcut xmlstream xmlstreamreader xmlstreamwriter textdate datestring process processenvironment temporaryfile settings filesystemwatcher filesystemiterator itemmodel proxymodel sortfilterproxymodel identityproxymodel transposeproxymodel concatenatetablesproxymodel stringlistmodel translation easingcurve animation gestures jalalicalendar islamiccivilcalendar timezone commandlineparser cborstreamreader cborstreamwriter permissions version_tagging static cross_compile pkg-config signaling_nan future concurrent test_gui test_squish static cross_compile intelcet glibc_fortify_source trivial_auto_var_init_pattern stack_protector stack_clash_protection libstdcpp_assertions static reduce_exports
QT.core.disabled_features = clock-monotonic cxx11_future cxx17_filesystem glib inotify jemalloc sharedmemory systemsemaphore cpp-winrt library timezone_tzdb shared debug_and_release separate_debug_info appstore-compliant simulator_and_device rpath force_asserts framework c++20 c++2a c++2b c++2c reduce_relocations wasm-simd128 wasm-exceptions wasm-jspi zstd thread dbus openssl-linked opensslv11 opensslv30
QT_CONFIG += std-atomic64 mimetype shortcut xmlstream xmlstreamreader xmlstreamwriter textdate datestring process processenvironment temporaryfile settings filesystemwatcher filesystemiterator itemmodel proxymodel sortfilterproxymodel identityproxymodel transposeproxymodel concatenatetablesproxymodel stringlistmodel translation easingcurve animation gestures jalalicalendar islamiccivilcalendar timezone commandlineparser cborstreamreader cborstreamwriter permissions version_tagging static cross_compile pkg-config signaling_nan future concurrent test_gui test_squish static cross_compile intelcet glibc_fortify_source trivial_auto_var_init_pattern stack_protector stack_clash_protection libstdcpp_assertions static reduce_exports
QT_MODULES += core

