# CodeOS fetch package manager configuration
# See: fetch help

[core]
Server = file:///.pkg/core

[extra]
Server = file:///.pkg/extra

[dev]
Server = file:///.pkg/dev

[util]
Server = file:///.pkg/util

[ccp]
Server = https://ccp.codeos.dev/rpc
