MAKEFILE_GENERATOR = UNIX
CONFIG += incremental
QMAKE_INCREMENTAL_PRELINK_DEPS =
QMAKE_INCREMENTAL_LFLAGS =

QMAKE_CC = x86_64-elf-gcc
QMAKE_CXX = x86_64-elf-g++
QMAKE_LINK = x86_64-elf-g++
QMAKE_LINK_SHLIB = x86_64-elf-g++

QMAKE_CFLAGS += -ffreestanding -fno-builtin -fno-stack-protector -nostdinc -nostdlib \
    -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2
QMAKE_CXXFLAGS += -ffreestanding -fno-builtin -fno-stack-protector -nostdinc -nostdlib \
    -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 \
    -std=c++17 -fno-exceptions -fno-rtti -fno-use-cxa-atexit
QMAKE_LFLAGS += -ffreestanding -nostdlib -z max-page-size=0x1000 -no-pie

QMAKE_LIBS += -L$$[QT_INSTALL_LIBS]

DEFINES += CODEOS_BUILD __codeos__ QT_NO_POSIX_IO QT_NO_PROCESS

include(../common/linux.conf)
