[Paths]
Prefix=../
Documentation=doc
Headers=include
Libraries=lib
LibraryExecutables=libexec
Binaries=bin
Plugins=plugins
QmlImports=qml
ArchData=.
Data=.
Translations=translations
Examples=examples
Tests=tests
Settings=etc/xdg
HostPrefix=../../../../../../../usr
HostBinaries=lib/qt6/bin
HostLibraries=lib
HostLibraryExecutables=lib/qt6
HostData=../home/codeosuser/CodeOS/qt6/sysroot/usr
Sysroot=
SysrootifyPrefix=false
TargetSpec=codeos-g++
HostSpec=linux-g++
